kind: Service
apiVersion: v1
metadata:
  name: solr-zookeeper
  namespace: stateful-set
  labels:
    app: zookeeper
    release: solr
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
      - name: client
        port: 2181
        protocol: TCP
        targetPort: client
  selector:
    app: zookeeper
    release: solr
