kind: Service
apiVersion: v1
metadata:
  name: solr-zookeeper-headless
  namespace: stateful-test
  labels:
    app: zookeeper
    release: solr
spec:
  clusterIP: None
  type: ClusterIP
  sessionAffinity: None
  ports:
      - name: client
        port: 2181
        protocol: TCP
        targetPort: client
      - name: election
        port: 3888
        protocol: TCP
        targetPort: election
      - name: server
        port: 2888
        protocol: TCP
        targetPort: server
  selector:
    app: zookeeper
    release: solr