apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: solr-zookeeper
  namespace: stateful-test
  labels:
    app: zookeeper
    component: server
    release: solr
spec:
  selector:
    matchLabels:
      app: zookeeper
      component: server
      release: solr
  replicas: 3
  serviceName: solr-zookeeper-headless
  updateStrategy:
    type: RollingUpdate
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: zookeeper
        component: server
        release: solr
    spec:
      containers:
      - name: zookeeper
        image: zookeeper:3.5.5
        imagePullPolicy: IfNotPresent
        command:
            - /bin/bash
            - -xec
            - /config-scripts/run
        ports:
        - name: client
          containerPort: 2181
          protocol: TCP
        - name: election
          containerPort: 3888
          protocol: TCP
        - name: server
          containerPort: 2888
          protocol: TCP
        env:
        - name: ZK_REPLICAS
          value: "3"
        - name: JMXAUTH
          value: "false"
        - name: JMXDISABLE
          value: "false"
        - name: JMXPORT
          value: "1099"
        - name: JMXSSL
          value: "false"
        - name: ZK_SYNC_LIMIT
          value: "10"
        - name: ZK_TICK_TIME
          value: "2000"
        - name: ZOO_AUTOPURGE_PURGEINTERVAL
          value: "0"
        - name: ZOO_AUTOPURGE_SNAPRETAINCOUNT
          value: "3"
        - name: ZOO_INIT_LIMIT
          value: "5"
        - name: ZOO_MAX_CLIENT_CNXNS
          value: "60"
        - name: ZOO_PORT
          value: "2181"
        - name: ZOO_STANDALONE_ENABLED
          value: "false"
        - name: ZOO_TICK_TIME
          value: "2000"
        volumeMounts:
        - name: data
          mountPath: /var/lib/zookeeper
        - name: config
          mountPath: /config-scripts 
        livenessProbe:
          exec:
            command:
            - sh
            - /config-scripts/ok
          initialDelaySeconds: 20
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - sh
            - /config-scripts/ready
          initialDelaySeconds: 20
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
      terminationGracePeriodSeconds: 1800
      dnsPolicy: ClusterFirst
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      schedulerName: default-scheduler
      volumes:
      - name: config
        configMap:
          defaultMode: 365
          name: solr-zookeeper 
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      storageClassName: default
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 3Gi
