apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
    name: solr
  namespace: stateful-test
  labels:
    app.kubernetes.io/instance: solr
    app.kubernetes.io/name: solr
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: server
      app.kubernetes.io/instance: solr
      app.kubernetes.io/name: solr
