kind: Service
apiVersion: v1
metadata:
  name: solr-headless
  namespace: stateful-test
  labels:
    app.kubernetes.io/instance: solr
    app.kubernetes.io/name: solr
spec:
  clusterIP: None
  type: ClusterIP
  sessionAffinity: None
  ports:
      - name: solr-headless
        protocol: TCP
        port: 8983
        targetPort: 8983
  selector:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: solr
    app.kubernetes.io/name: solr
