kind: Service
apiVersion: v1
metadata:
  name: solr-svc
  namespace: stateful-test
  labels:
    app.kubernetes.io/instance: solr
    app.kubernetes.io/name: solr
    app.kubernetes.io/managed-by: Tiller
    helm.sh/chart: solr-1.4.0
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
      - name: solr-client
        protocol: TCP
        port: 8983
        targetPort: 8983
  selector:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: solr
    app.kubernetes.io/name: solr
