kind: StatefulSet
apiVersion: apps/v1
metadata:
  labels:
    app.kubernetes.io/component: server
  name: solr
  namespace: stateful-test
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: server
      app.kubernetes.io/instance: solr
      app.kubernetes.io/name: solr
  replicas: 3
  revisionHistoryLimit: 0
  serviceName: solr-headless
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: server
        app.kubernetes.io/instance: solr
        app.kubernetes.io/name: solr
    spec:
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 128975361
        runAsNonRoot: true
        runAsUser: 83435
      affinity: {}
      terminationGracePeriodSeconds: 180
      dnsPolicy: ClusterFirst
      volumes:
          - name: solr-xml
            configMap:
              name: solr-config-map
              items:
              - key: solr.xml
                path: solr.xml
      initContainers:
        - name: check-zk
          image: busybox:latest
          imagePullPolicy: Always
          command:
            - sh
            - -c
            - |
              COUNTER=0;
              while [  $COUNTER -lt 120 ]; do
                addr=$(nslookup -type=a solr-zookeeper-headless | grep "Address:" | awk 'NR>1 {print $2}')
                if [ ! -z "$addr" ]; then
                  while read -r line; do
                    echo $line;
                    mode=$(echo srvr | nc $line 2181 | grep "Mode");
                    echo $mode;
                    if [ "$mode" = "Mode: leader" ] || [ "$mode" = "Mode: standalone" ]; then
                      echo "Found a leader!";
                      exit 0;
                    fi;
                  done <<EOF
              $addr
              EOF
                fi;
                let COUNTER=COUNTER+1;
                sleep 2;
              done;
              echo "Did NOT see a ZK leader after 240 secs!";
              exit 1;
      containers:
        - name: solr
          image: solr:8.4.0
          imagePullPolicy: IfNotPresent
          args: ["cloud"]
          ports:
            - name: solr-client
              containerPort: 8983
              protocol: TCP
          env:
            - name: SOLR_JAVA_MEM
              value: -Xms2g -Xmx3g
            - name: SOLR_HOME
              value: /opt/solr/server/home
            - name: SOLR_PORT
              value: "8983"
            - name: POD_HOSTNAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: SOLR_HOST
              value: $(POD_HOSTNAME).solr-headless.default
            - name: ZK_HOST
              value: solr-zookeeper-headless:2181
            - name: SOLR_LOG_LEVEL
              value: INFO
          securityContext:
            fsGroup: 128975361
            runAsNonRoot: true
            runAsUser: 83435
          volumeMounts:
            - name: solr-pvc
              mountPath: /var/solr/data
          livenessProbe:
            httpGet:
              path: /solr
              port: 8983
              scheme: HTTP
            initialDelaySeconds: 45
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /solr
              port: 8983
              scheme: HTTP
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
        imagePullSecrets:
        - name: acrpullsecret
  volumeClaimTemplates:
    - metadata:
        name: solr-pvc
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 3Gi
